eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
    
/* Just checking*/   
    
/*Token which cexpires on Oct 24 2025:*/